//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 11:20:40 PM CST 
//


package com.tutorialspoint.webservice.countryservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tutorialspoint.webservice.countryservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AllCountryDetailsRequest_QNAME = new QName("http://tutorialspoint.com/webservice/countryservice", "AllCountryDetailsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tutorialspoint.webservice.countryservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddCountryDetailsResponse }
     * 
     */
    public AddCountryDetailsResponse createAddCountryDetailsResponse() {
        return new AddCountryDetailsResponse();
    }

    /**
     * Create an instance of {@link CountryDetailsResponse }
     * 
     */
    public CountryDetailsResponse createCountryDetailsResponse() {
        return new CountryDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateCountryDetailsRequest }
     * 
     */
    public UpdateCountryDetailsRequest createUpdateCountryDetailsRequest() {
        return new UpdateCountryDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteCountryDetailsRequest }
     * 
     */
    public DeleteCountryDetailsRequest createDeleteCountryDetailsRequest() {
        return new DeleteCountryDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteCountryDetailsResponse }
     * 
     */
    public DeleteCountryDetailsResponse createDeleteCountryDetailsResponse() {
        return new DeleteCountryDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateCountryDetailsResponse }
     * 
     */
    public UpdateCountryDetailsResponse createUpdateCountryDetailsResponse() {
        return new UpdateCountryDetailsResponse();
    }

    /**
     * Create an instance of {@link AllCountryDetailsResponse }
     * 
     */
    public AllCountryDetailsResponse createAllCountryDetailsResponse() {
        return new AllCountryDetailsResponse();
    }

    /**
     * Create an instance of {@link CountryDetailsRequest }
     * 
     */
    public CountryDetailsRequest createCountryDetailsRequest() {
        return new CountryDetailsRequest();
    }

    /**
     * Create an instance of {@link AddCountryDetailsRequest }
     * 
     */
    public AddCountryDetailsRequest createAddCountryDetailsRequest() {
        return new AddCountryDetailsRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tutorialspoint.com/webservice/countryservice", name = "AllCountryDetailsRequest")
    public JAXBElement<Object> createAllCountryDetailsRequest(Object value) {
        return new JAXBElement<Object>(_AllCountryDetailsRequest_QNAME, Object.class, null, value);
    }

}
