//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 11:20:40 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tutorialspoint.com/webservice/countryservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tutorialspoint.webservice.countryservice;
